### ISSUE TITLE
Server issues?

### ISSUE THREAD

**Issue by vsoch** [danger89/fake-useragent#9]
Heyo! I was attempting to install this updated version, and I think there is either a bug or I'm erroneously using the old repository. Here is the bug:

https://github.com/urlstechie/urlchecker-action/runs/7908855698?check_suite_focus=true

```
urlchecker check  --branch master --subfolder test_action --no-print --file-types .md --retry-count 1 --timeout 5 --save results.csv --force-pass https://github.com/urlstechie/urlchecker-test-repo
           original path: https://github.com/urlstechie/urlchecker-test-repo
              final path: /tmp/urlchecker-test-repo.63a6fmas/test_action
               subfolder: test_action
                  branch: master
                 cleanup: False
                  serial: False
              file types: ['.md']
                   files: []
               print all: False
                 verbose: False
           urls excluded: []
   url patterns excluded: []
  file patterns excluded: []
              force pass: True
             retry count: 1
                    save: results.csv
                 timeout: 5
WARNING:fake_useragent:Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.12
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/fake_useragent/utils.py", line 166, in load
    browsers_dict[browser_key] = get_browser_versions(
  File "/opt/conda/lib/python3.9/site-packages/fake_useragent/utils.py", line 145, in get_browser_versions
    raise FakeUserAgentError(
fake_useragent.errors.FakeUserAgentError: No browsers version found for Chrome
WARNING:fake_useragent:Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.12
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/fake_useragent/utils.py", line 166, in load
    browsers_dict[browser_key] = get_browser_versions(
  File "/opt/conda/lib/python3.9/site-packages/fake_useragent/utils.py", line 145, in get_browser_versions
    raise FakeUserAgentError(
fake_useragent.errors.FakeUserAgentError: No browsers version found for Chrome
2022-08-18 23:03:03,589 - urlchecker - ERROR - Error running task
🤔 There were no URLs to check.
ERROR:urlchecker:Error running task
Exception ignored in: <function Pool.__del__ at 0x7faa95431160>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/multiprocessing/pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "/opt/conda/lib/python3.9/multiprocessing/queues.py", line 378, in put
    self._writer.send_bytes(obj)
  File "/opt/conda/lib/python3.9/multiprocessing/connection.py", line 205, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/opt/conda/lib/python3.9/multiprocessing/connection.py", line 416, in _send_bytes
    self._send(header + buf)
  File "/opt/conda/lib/python3.9/multiprocessing/connection.py", line 373, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
```
Specifically this is the start:

```bash
fake_useragent.errors.FakeUserAgentError: No browsers version found for Chrome
```
Could you let me know if you have a sense of which case it might be? Thank you!

**Comment by vsoch** [comment]
oup - so it looks like it's the old library - uninstall then install fixed it! Sorry for the noise!
